# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'agent-001'
  demands:
  - agent.name -equals agent


steps:
- script: echo Hello, Akza!
  displayName: 'Run a one-line script'

- script: |
    pip install -r requirements.txt
    python3 -m app.py
  displayName: 'Run a multi-line script'
